print("___________________°")
print("_________________°Paz°")
print("________________°União°")
print("_______________°Alegrias°")
print("______________°Esperanças°")
print("_____________°Amor°Sucesso°")
print("____________°Realizações°Luz°")
print("___________°Respeito°harmonia°")
print("__________°Saúde°solidariedade°")
print("_________°Felicidade°-°Humildade°")
print("________°Confraternização-°Pureza°")
print("_______°Amizade° Sabedoria ° Perdão°")
print("______°Igualdade° Liberdade° Boasorte°")
print("_____°Sinceridade-°Estima-°Fraternidade°")
print("____°Equilíbrio- °Dignidade-Benevolência°")
print("___°Fé°Bondade°Paciência°Brandura°Força°H")
print("__°Tenacidade°Prosperidade°Reconhecimento°")
print("_______________°°°°°°°°°°°°____________________")
print("_______________°°°°°°°°°°°°____________________")
print("_______________°°°°°°°°°°°°____________________")
print("_______________°°°°°°°°°°°°____________________")
print("________________♥JESUS♥_________________")
