Nome= (input('digite seu nome e sobrenome:'))
Idade= (input('digite sua idade:'))
RA= (input('digite seu RA:'))
nota1= float (input('digite sua primeira nota:'))
nota2= float (input('digite sua segunda nota:'))
nota3= float (input('digite sua terceira nota:'))
nota4= float (input('digite sua quarta nota:'))
media= (nota1+nota2+nota3+nota4)/4
print(Nome, Idade, RA)
print('sua média final é de:', media)