print('TABUADA DO SEU NÚMERO')
num= int (input('Digite um número de sua escolha:'))
print('NÚMERO X 1=',(num*1))
print('NÚMERO X 2=',(num*2))
print('NÚMERO X 3=',(num*3))
print('NÚMERO X 4=',(num*4))
print('NÚMERO X 5=',(num*5))
print('NÚMERO X 6=',(num*6))
print('NÚMERO X 7=',(num*7))
print('NÚMERO X 8=',(num*8))
print('NÚMERO X 9=',(num*9))
print('NÚMERO X 10=',(num*10))